<?php
$itemid=(int)($_GET['item_id']??0);$orderid=(int)($_GET['order_id']??0);$contextLabel='No linked order';
if($itemid){$item=must('items',$itemid);$orderid=(int)$item['order_id'];$contextLabel='Item: '.$item['name'];}elseif($orderid){$order=must('orders',$orderid);$contextLabel='Order: '.$order['code'];}
$draft=$_SESSION['ai_draft']??[];if(($draft['item_id']??0)!==$itemid||($draft['order_id']??0)!==$orderid)$draft=[];
$enabled=!empty($config['ai']['key'])&&!empty($config['ai']['model']);
?><div class="columns"><section class="card"><h2>Write, extract, organize</h2><p class="muted"><?=e($contextLabel)?>. Open the assistant from an order or item to include saved requirements and progress.</p><div class="alert">AI is <?=$enabled?'enabled':'not configured'?>. <?php if(!$enabled): ?><a href="index.php?page=settings#ai-setup">Set up AI first</a>.<?php endif ?> Generating a draft sends your pasted text and linked order/item details to the configured AI provider. Your selected PDF or image is also sent; unselected order files and product images are not sent. Review every draft before use.</div>
<?php startform('ai',['item_id'=>$itemid,'order_id'=>$orderid],true); ?><label>Task<?php selectbox('task',['instructions'=>'Read and follow sheet instructions','write'=>'Write clear requirements','organize'=>'Organize details','extract'=>'Extract from PDF, image or text','followup'=>'Draft buyer follow-up','next'=>'Suggest next actions','steps'=>'Suggest production steps'],$_POST['task']??$_GET['task']??'organize'); ?></label><?php area('Instructions / pasted buyer text (optional when using a file)','input',$_POST['input']??'',6); ?>
<label>Upload a PDF, JPG or PNG · maximum 5 MB<input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"></label>
<?php if($orderid): ?><label>Or select a saved order / product sheet<select name="file_id"><option value="">No saved file selected</option><?php foreach(rows('SELECT id,original_name FROM order_files WHERE order_id=? ORDER BY id DESC',[$orderid]) as $file): ?><option value="<?=$file['id']?>" <?=($_POST['file_id']??$_GET['file_id']??0)==$file['id']?'selected':''?>><?=e($file['original_name'])?></option><?php endforeach ?></select></label><?php endif ?><button <?=$enabled?'':'disabled'?>>Generate draft</button><button id="ai-cancel" type="button" class="secondary" hidden>Cancel wait</button><div id="ai-status" role="status" aria-live="polite" hidden></div></form><p class="muted">Choose either one new upload or one saved sheet. Direct assistant uploads are used for this request only; upload through the order form to keep a copy. PDF/image extraction requires a vision-capable model. Review unclear measurements and quantities. Follow-ups are drafts and are never sent automatically.</p></section>
<section class="card"><h2>Draft for review</h2><?php if($draft): ?><textarea id="ai-result" rows="16"><?=e($draft['text'])?></textarea><button class="secondary" type="button" data-copy="ai-result">Copy draft</button><p id="copy-status" class="muted" role="status"></p>
<?php if(($draft['task']??'')==='steps'&&$itemid):startform('apply_steps',['item_id'=>$itemid]);area('Review sequence · one step per line','steps',$draft['text'],10); ?><button>Add reviewed production steps</button></form><?php elseif($orderid):startform('note',['order_id'=>$orderid]);area('Edit draft and save as an order note','body',$draft['text'],8);field('Optional follow-up date','followup_date','','date'); ?><button>Save reviewed note</button></form><?php endif ?>
<?php else: ?><p class="muted">Your last draft for this order or item will appear here. AI does not change orders by itself.</p><?php endif ?></section></div>
