<?php
$itemid=(int)($_GET['item_id']??0);$orderid=(int)($_GET['order_id']??0);$contextLabel='No linked order';
if($itemid){$item=must('items',$itemid);$orderid=(int)$item['order_id'];$contextLabel='Item: '.$item['name'];}elseif($orderid){$order=must('orders',$orderid);$contextLabel='Order: '.$order['code'];}
$draft=$_SESSION['ai_draft']??[];if(($draft['item_id']??0)!==$itemid||($draft['order_id']??0)!==$orderid)$draft=[];
$enabled=!empty($config['ai']['key'])&&!empty($config['ai']['model']);
?><div class="columns"><section class="card"><h2>Write, extract, organize</h2><p class="muted"><?=e($contextLabel)?>. Open the assistant from an order or item to include saved requirements and progress.</p><div class="alert">AI is <?=$enabled?'enabled':'not configured'?>. Generating a draft sends your pasted text and linked order/item details to the configured AI provider. Product images are not sent. Review every draft before use.</div>
<?php startform('ai',['item_id'=>$itemid,'order_id'=>$orderid]); ?><label>Task<?php selectbox('task',['write'=>'Write clear requirements','organize'=>'Organize details','extract'=>'Extract from pasted text','followup'=>'Draft buyer follow-up','next'=>'Suggest next actions','steps'=>'Suggest production steps'],$_POST['task']??$_GET['task']??'organize'); ?></label><?php area('Paste buyer email, WhatsApp text, notes or your request','input',$_POST['input']??'',10); ?><button <?=$enabled?'':'disabled'?>>Generate draft</button></form><p class="muted">Text extraction only in this MVP. Copy text from documents into this field. Follow-ups are drafts and are never sent automatically.</p></section>
<section class="card"><h2>Draft for review</h2><?php if($draft): ?><textarea id="ai-result" rows="16"><?=e($draft['text'])?></textarea><button class="secondary" type="button" data-copy="ai-result">Copy draft</button><p id="copy-status" class="muted" role="status"></p>
<?php if(($draft['task']??'')==='steps'&&$itemid):startform('apply_steps',['item_id'=>$itemid]);area('Review sequence · one step per line','steps',$draft['text'],10); ?><button>Add reviewed production steps</button></form><?php elseif($orderid):startform('note',['order_id'=>$orderid]);area('Edit draft and save as an order note','body',$draft['text'],8);field('Optional follow-up date','followup_date','','date'); ?><button>Save reviewed note</button></form><?php endif ?>
<?php else: ?><p class="muted">Your last draft for this order or item will appear here. AI does not change orders by itself.</p><?php endif ?></section></div>
