<?php
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month)||(int)substr($month,0,4)<2000||(int)substr($month,0,4)>2100)$month=date('Y-m');
$first=new DateTimeImmutable($month.'-01');$last=$first->modify('last day of this month');$range=[$first->format('Y-m-d'),$last->format('Y-m-d')];$events=[];
$queries=[
 ['SELECT id,code title,due_date day FROM orders WHERE due_date BETWEEN ? AND ? AND status NOT IN (\'shipped\',\'cancelled\')','order','Completion'],
 ['SELECT id,code title,ship_date day FROM orders WHERE ship_date BETWEEN ? AND ? AND status NOT IN (\'shipped\',\'cancelled\')','order','Shipping'],
 ['SELECT s.item_id id,CONCAT(i.name,\' · \',s.name) title,s.due_date day FROM item_steps s JOIN items i ON i.id=s.item_id JOIN orders o ON o.id=i.order_id WHERE s.due_date BETWEEN ? AND ? AND s.status<>\'done\' AND o.status NOT IN (\'shipped\',\'cancelled\')','item','Production'],
 ['SELECT c.item_id id,CONCAT(i.name,\' · \',c.name) title,c.due_date day FROM components c JOIN items i ON i.id=c.item_id JOIN orders o ON o.id=i.order_id WHERE c.due_date BETWEEN ? AND ? AND c.status<>\'done\' AND o.status NOT IN (\'shipped\',\'cancelled\')','item','Component'],
 ['SELECT order_id id,body title,followup_date day FROM notes n JOIN orders o ON o.id=n.order_id WHERE followup_date BETWEEN ? AND ? AND done=0 AND o.status NOT IN (\'shipped\',\'cancelled\')','order','Follow-up'],
 ['SELECT i.order_id id,i.name title,i.due_date day FROM items i JOIN orders o ON o.id=i.order_id WHERE i.due_date BETWEEN ? AND ? AND o.status NOT IN (\'shipped\',\'cancelled\')','order','Item due']
];
foreach($queries as [$sql,$link,$kind])foreach(rows($sql,$range) as $ev){$ev['link']=$link;$ev['kind']=$kind;$events[$ev['day']][]=$ev;}ksort($events);
?><div class="toolbar"><a class="button secondary" href="index.php?page=calendar&month=<?=$first->modify('-1 month')->format('Y-m')?>">← Previous</a><form method="get" class="inline"><input type="hidden" name="page" value="calendar"><input type="month" name="month" value="<?=e($month)?>"><button>Show month</button></form><a class="button secondary" href="index.php?page=calendar&month=<?=$first->modify('+1 month')->format('Y-m')?>">Next →</a></div>
<section class="card"><h2><?=e($first->format('F Y'))?></h2><p class="muted">Schedule comes from order, item, component, step and follow-up dates. Open an entry to edit its deadline.</p><div class="calendar"><?php foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day): ?><div class="day-name"><?=$day?></div><?php endforeach ?><?php for($x=1;$x<(int)$first->format('N');$x++): ?><div class="day blank"></div><?php endfor ?><?php for($day=1;$day<=(int)$last->format('j');$day++):$key=$month.'-'.str_pad((string)$day,2,'0',STR_PAD_LEFT); ?><div class="day <?=$key===date('Y-m-d')?'today':''?>"><b><?=$day?></b><?php foreach($events[$key]??[] as $ev): ?><a href="index.php?page=<?=e($ev['link'])?>&id=<?=$ev['id']?>"><small><?=e($ev['kind'])?></small><?=e(mb_strimwidth($ev['title'],0,80,'…'))?></a><?php endforeach ?></div><?php endfor ?></div></section>
<section class="card"><h2>Month agenda</h2><?php if(!$events): ?><p class="muted">No scheduled work this month.</p><?php endif ?><?php foreach($events as $day=>$entries): ?><h3><?=e($day)?></h3><?php foreach($entries as $ev): ?><p><span class="badge"><?=e($ev['kind'])?></span> <a href="index.php?page=<?=e($ev['link'])?>&id=<?=$ev['id']?>"><?=e($ev['title'])?></a></p><?php endforeach;endforeach ?></section>
