<?php
$id=(int)($_GET['id']??0);$i=$id?must('items',$id):['order_id'=>(int)($_GET['order_id']??0),'quantity'=>1];$order=must('orders',(int)$i['order_id']);
if(($_POST['action']??'')==='item'&&isset($error))$i=$_POST;
$types=rows('SELECT * FROM component_types ORDER BY name');$templates=rows('SELECT * FROM step_templates WHERE active=1 ORDER BY position,id');
$components=$id?rows('SELECT c.*,t.name type_name FROM components c JOIN component_types t ON t.id=c.type_id WHERE item_id=? ORDER BY c.id',[$id]):[];
?><div class="toolbar"><a href="index.php?page=order&id=<?=$order['id']?>">← <?=e($order['code'])?></a><?php if($id): ?><a class="button secondary" href="index.php?page=assistant&item_id=<?=$id?>">Help with this item</a><?php endif ?></div>
<section class="card"><h2><?=$id?e($i['name']):'New product item'?></h2><?php startform('item',['id'=>$id?:'','order_id'=>$order['id']],true); ?><div class="form-grid"><?php field('Product name','name',$i['name']??'','text',true,'maxlength="160"');field('SKU / style code','sku',$i['sku']??'');field('Quantity','quantity',$i['quantity'],'number',true,'min="1" max="1000000" step="1"');field('Fabric / composition / GSM','fabric',$i['fabric']??'');field('Colors / Pantone','colors',$i['colors']??'');field('Item due date','due_date',$i['due_date']??'','date'); ?></div><?php area('Size breakdown (e.g. S:20, M:30)','sizes',$i['sizes']??'');area('Detailed requirements: design, logo size & placement, printing, packing','requirements',$i['requirements']??''); ?><label>Product image · JPG / PNG / WebP, maximum 5 MB<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><button>Save item</button></form></section>
<?php if($id):$images=rows('SELECT * FROM images WHERE item_id=?',[$id]); ?>
<section class="card"><h2>Product references</h2><div class="gallery"><?php foreach($images as $img): ?><a href="index.php?image=<?=$img['id']?>" target="_blank" rel="noopener"><img src="index.php?image=<?=$img['id']?>" alt="<?=e($img['original_name'])?>"><small><?=e($img['original_name'])?></small></a><?php endforeach ?></div><?php if(!$images): ?><p class="muted">Upload the design or product photo to keep the reference beside its requirements.</p><?php endif ?><?php startform('image',['item_id'=>$id],true); ?><div class="inline"><input type="file" name="image" accept="image/jpeg,image/png,image/webp" required><button class="secondary">Add image</button></div></form></section>
<section class="card"><h2>Accessories & components</h2><p class="muted">Track each logo, button or label separately. Add custom types in Settings.</p>
<?php foreach($components as $c): ?><details><summary><?=e($c['type_name'].' · '.$c['name'])?> <span><?=e(str_replace('_',' ',$c['status']))?> · <?=$c['quantity']?> units</span></summary><?php component_form($c,$id,$types); ?></details><?php endforeach ?>
<details <?=!$components?'open':''?>><summary>+ New component</summary><?php component_form(($_POST['action']??'')==='component'&&isset($error)?$_POST:[],$id,$types); ?></details></section>
<section class="card"><h2>Item production workflow</h2><p class="muted">Edit the position number to reorder. Steps are independent; resolve prerequisites before starting later work.</p>
<?php $steps=rows('SELECT * FROM item_steps WHERE item_id=? ORDER BY position,id',[$id]);foreach($steps as $s): ?><details><summary><b><?=e($s['position'])?>. <?=e($s['name'])?></b><span><?=e(str_replace('_',' ',$s['status']))?><?= $s['due_date']?' · '.e($s['due_date']):'' ?></span></summary><?php step_form($s,$id); ?></details><?php endforeach ?>
<details><summary>+ Add a custom step</summary><?php step_form(($_POST['action']??'')==='step'&&isset($error)?$_POST:['position'=>count($steps)*10+10],$id); ?></details>
<div class="columns inner"><div><h3>Suggested sequence</h3><p class="muted">Built-in suggestions use requirement keywords. Review and edit before adding. Existing steps keep their status.</p><?php startform('apply_steps',['item_id'=>$id]);area('One step name per line','steps',($_POST['action']??'')==='apply_steps'&&isset($error)?($_POST['steps']??''):implode("\n",suggestions($i,$components,$templates)),8); ?><button class="secondary">Add reviewed steps</button></form></div><div><h3>Available step templates</h3><p class="muted"><?=e(implode(' · ',array_column($templates,'name')))?></p><a href="index.php?page=settings">Configure templates</a><p><a href="index.php?page=assistant&item_id=<?=$id?>&task=steps">Ask AI for a sequence →</a></p></div></div></section>
<?php endif;
function component_form(array $c,int $item,array $types):void{
 startform('component',['id'=>$c['id']??'','item_id'=>$item]);echo '<div class="form-grid"><label>Type<select name="type_id" required>';foreach($types as $t)echo '<option value="'.$t['id'].'"'.(($c['type_id']??'')==$t['id']?' selected':'').'>'.e($t['name']).'</option>';echo '</select></label>';
 field('Name / reference','name',$c['name']??'','text',true,'maxlength="160"');field('Quantity','quantity',$c['quantity']??1,'number',true,'min="1" step="1"');echo '<label>Status';selectbox('status',statuses(),$c['status']??'pending');echo '</label>';field('Supplier / maker','supplier',$c['supplier']??'');field('Due date','due_date',$c['due_date']??'','date');echo '</div>';area('Size, material, position, color, attachment method','details',$c['details']??'');echo '<button>Save component</button></form>';
}
function step_form(array $s,int $item):void{
 startform('step',['id'=>$s['id']??'','item_id'=>$item]);echo '<div class="form-grid">';field('Step name','name',$s['name']??'','text',true,'maxlength="100"');field('Position','position',$s['position']??10,'number',true,'min="0" max="9999"');echo '<label>Status';selectbox('status',statuses(),$s['status']??'pending');echo '</label>';field('Assigned to','assignee',$s['assignee']??'');field('Start date','start_date',$s['start_date']??'','date');field('Due date','due_date',$s['due_date']??'','date');echo '</div>';area('Progress / blockers / approval notes','notes',$s['notes']??'');if(!empty($s['completed_at']))echo '<p class="muted">Completed '.e($s['completed_at']).'</p>';echo '<button>Save step</button></form>';
}
