<?php
$id=(int)($_GET['id']??0);$o=$id?must('orders',$id):['code'=>'AW-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(2))),'order_date'=>date('Y-m-d'),'status'=>'draft','priority'=>'normal'];
if(($_POST['action']??'')==='order'&&isset($error))$o=$_POST;
$customers=rows('SELECT id,name FROM customers ORDER BY name');
?><div class="toolbar"><a href="index.php?page=orders">← Orders</a><?php if($id): ?><a class="button secondary" href="index.php?page=assistant&order_id=<?=$id?>">Help with this order</a><?php endif ?></div>
<?php if(!$customers): ?><div class="alert">Add a <a href="index.php?page=customers">customer</a> before creating an order.</div><?php endif ?>
<section class="card"><h2><?=e($o['code'])?></h2><?php startform('order',['id'=>$id?:'']); ?><div class="form-grid"><?php field('Order number','code',$o['code'],'text',true,'maxlength="80"'); ?><label>Customer<select name="customer_id" required><option value="">Select customer</option><?php foreach($customers as $c): ?><option value="<?=$c['id']?>" <?=($o['customer_id']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach ?></select></label><label>Order status<?php selectbox('status',['draft','confirmed','production','ready','shipped','cancelled'],$o['status']); ?></label><label>Priority<?php selectbox('priority',['normal','high','urgent'],$o['priority']); ?></label><?php field('Order date','order_date',$o['order_date'],'date',true);field('Completion date','due_date',$o['due_date']??'','date');field('Shipping date','ship_date',$o['ship_date']??'','date');field('Destination country / zone','destination',$o['destination']??'');field('Courier / tracking reference','tracking',$o['tracking']??''); ?></div><?php area('Order instructions / packing / commercial details','details',$o['details']??''); ?><button>Save order</button></form><p class="muted">Order status is set manually. Item progress is calculated from its production checklist.</p></section>
<?php if($id):$items=rows('SELECT * FROM items WHERE order_id=? ORDER BY id',[$id]); ?>
<section class="card"><div class="toolbar"><h2>Order items</h2><a class="button" href="index.php?page=item&order_id=<?=$id?>">+ Add item</a></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Fabric / colors</th><th>Production progress</th><th>Due</th></tr></thead><tbody><?php foreach($items as $i):$p=progress((int)$i['id']); ?><tr><td><a href="index.php?page=item&id=<?=$i['id']?>"><?=e($i['name'])?></a><small><?=e($i['sku'])?></small></td><td><?=$i['quantity']?></td><td><?=e($i['fabric'])?><small><?=e($i['colors'])?></small></td><td><?=e($p['done']??0)?> / <?=e($p['total'])?> steps <progress value="<?=e($p['done']??0)?>" max="<?=max(1,(int)$p['total'])?>"></progress></td><td><?=e($i['due_date'])?></td></tr><?php endforeach ?><?php if(!$items): ?><tr><td colspan="5">Add your first product item, then define its components and production steps.</td></tr><?php endif ?></tbody></table></div></section>
<div class="columns"><section class="card"><h2>Notes & follow-ups</h2><?php startform('note',['order_id'=>$id]);area('Note / next action','body',($_POST['action']??'')==='note'?($_POST['body']??''):'');field('Follow-up date (optional)','followup_date',($_POST['action']??'')==='note'?($_POST['followup_date']??''):'','date'); ?><button>Add note</button></form></section><section class="card"><h2>Order timeline</h2><?php foreach(rows('SELECT * FROM notes WHERE order_id=? ORDER BY id DESC',[$id]) as $n): ?><article class="note"><p><?=nl2br(e($n['body']))?></p><small><?=e($n['created_at'])?><?= $n['followup_date']?' · Follow up '.e($n['followup_date']):'' ?></small><?php startform('note_done',['id'=>$n['id']]); ?><button class="quiet"><?=$n['done']?'Completed · Reopen':'Mark complete'?></button></form></article><?php endforeach ?></section></div><?php endif ?>
