<div class="columns"><section class="card"><h2>Production step templates</h2><p class="muted">Templates are available for future workflows. Renaming or disabling a template leaves saved item steps intact.</p><?php foreach(rows('SELECT * FROM step_templates ORDER BY position,id') as $t): ?><details><summary><?=e($t['position'].' · '.$t['name'])?><span><?=$t['active']?'Active':'Disabled'?></span></summary><?php template_form($t); ?></details><?php endforeach ?><details><summary>+ New template</summary><?php template_form(($_POST['action']??'')==='template'&&isset($error)?$_POST:[]); ?></details></section>
<section class="card"><h2>Component types</h2><div class="chips"><?php foreach(rows('SELECT * FROM component_types ORDER BY name') as $t): ?><span class="badge"><?=e($t['name'])?></span><?php endforeach ?></div><?php startform('component_type');field('Custom component type','name',($_POST['action']??'')==='component_type'?($_POST['name']??''):'','text',true,'maxlength="100"'); ?><button>Add type</button></form><h3>AI configuration</h3><p class="muted">AI is <?=!empty($config['ai']['key'])&&!empty($config['ai']['model'])?'configured':'disabled'?>. Use the AI setup form below to enter a key and model. Secrets are never sent to the browser.</p></section></div>
<section class="card" id="ai-setup"><h2>AI setup</h2><p>Use your eligible ChatGPT Plus/Pro subscription without adding separate API credits. Sign in once below, choose ChatGPT subscription, and save. Usage counts against your plan's shared limits. No automatic switch to a paid API occurs.</p>
<?php $chatgpt=chatgpt_record((int)$_SESSION['user']['id']); ?><p><?=!empty($chatgpt['access_token'])?'Connected ChatGPT account: '.e($chatgpt['email']):'Your ChatGPT account is not connected yet.'?></p>
<?php startform('chatgpt_connect'); ?><button>Continue with ChatGPT</button><p id="chatgpt-status" role="status" aria-live="polite" hidden></p><a id="chatgpt-link" target="_blank" rel="noopener noreferrer" hidden>Open ChatGPT sign-in</a></form><p class="muted">Complete sign-in in your browser, then return to this tab and refresh. Being signed into ChatGPT does not yet authorize Aini Wear. The connection belongs to your Aini Wear staff login. Authorize plan usage and leave credit spending disabled in ChatGPT. <a href="https://chatgpt.com/settings/usage" target="_blank" rel="noopener noreferrer">Manage ChatGPT app usage</a></p>
<?php if(!empty($chatgpt['access_token'])):startform('chatgpt_models'); ?><button class="secondary">Load available subscription models</button></form><?php endif ?>
<?php startform('ai_settings'); ?><label>AI service<?php selectbox('provider',['chatgpt'=>'ChatGPT subscription · no API credits','openai'=>'OpenAI API · separate billing'],$_POST['provider']??$config['ai']['provider']??'openai'); ?></label>
<?php field(!empty($config['ai']['key'])?'Optional replacement API key (API service only)':'API key (API service only)','api_key','','password',false,'autocomplete="new-password" maxlength="512"');field('Model ID','model',($_POST['action']??'')==='ai_settings'?($_POST['model']??''):($config['ai']['model']??'gpt-6.1-sol'),'text',true,'maxlength="100" list="chatgpt-models"'); ?><datalist id="chatgpt-models"><?php foreach($_SESSION['chatgpt_models']??[] as $m): ?><option value="<?=e($m['slug'])?>"><?=e($m['display_name']??$m['slug'])?></option><?php endforeach ?></datalist><button>Save AI settings</button></form><p class="muted">All staff can change the service and model. ChatGPT tokens and API keys stay in private server storage and are never displayed.</p></section>
<?php function template_form(array $t):void{startform('template',['id'=>$t['id']??'']);field('Name','name',$t['name']??'','text',true,'maxlength="100"');field('Position','position',$t['position']??10,'number',true,'min="0" max="9999"');echo '<label class="check"><input type="checkbox" name="active" '.(($t['active']??1)?'checked':'').'>Active</label><button>Save template</button></form>';} ?>
