<?php
$destination=mb_substr(trim((string)($_GET['destination']??'')),0,100);$currency=strtoupper(trim((string)($_GET['currency']??'USD')));$weight=(float)($_GET['weight']??1);$mode=(string)($_GET['mode']??'balanced');$maxdays=(int)($_GET['maxdays']??0);$rank=[];
if($destination!==''&&preg_match('/^[A-Z]{3}$/',$currency)&&is_finite($weight)&&$weight>0&&$weight<=1000000){$sql='SELECT * FROM shipping_rates WHERE active=1 AND destination=? AND currency=? AND min_kg<? AND max_kg>=? AND (valid_until IS NULL OR valid_until>=CURDATE())';$args=[$destination,$currency,$weight,$weight];if($maxdays>0){$sql.=' AND transit_days>0 AND transit_days<=?';$args[]=$maxdays;}$rank=rank_rates(rows($sql,$args),$mode==='fastest'?1:($mode==='cheapest'?0:0.5));}
$edit=!empty($_GET['edit'])?must('shipping_rates',(int)$_GET['edit']):[];if(($_POST['action']??'')==='rate'&&isset($error))$edit=$_POST;
?><section class="card"><h2>Find the right service</h2><form method="get"><input type="hidden" name="page" value="shipping"><div class="form-grid"><?php field('Destination (exact country / zone)','destination',$destination,'text',true);field('Chargeable weight (kg)','weight',$weight,'number',true,'min="0.001" step="0.001"');field('Currency','currency',$currency,'text',true,'pattern="[A-Za-z]{3}" maxlength="3"');field('Maximum transit days (blank = any)','maxdays',$maxdays?:'','number',false,'min="1" max="365"'); ?><label>Preference<?php selectbox('mode',['balanced','cheapest','fastest'],$mode); ?></label></div><button>Compare rates</button></form>
<p class="muted">Rates are flat totals for the selected slab: minimum exclusive, maximum inclusive. Balanced uses 50% normalized cost + 50% normalized transit time (lower score wins). Compare one currency at a time. Unknown transit times use 0, appear last for balanced/fastest comparisons, and are excluded by a maximum-days filter. Transit days are courier estimates; taxes, surcharges, dimensional-weight rules and dispatch time must be checked separately.</p>
<?php if($destination): ?><div class="table-wrap"><table><thead><tr><th>Recommendation</th><th>Courier / service</th><th>Rate</th><th>Transit</th><th>Slab</th></tr></thead><tbody><?php foreach($rank as $n=>$r): ?><tr><td><?=$n===0?'Best match':'Alternative'?></td><td><?=e($r['courier'])?><small><?=e($r['service'])?></small></td><td><?=e($r['currency'].' '.number_format((float)$r['rate'],2))?></td><td><?=((int)$r['transit_days']===0?'Unknown':e($r['transit_days']).' days')?></td><td>&gt; <?=e($r['min_kg'])?> to <?=e($r['max_kg'])?> kg</td></tr><?php endforeach ?><?php if(!$rank): ?><tr><td colspan="5">No active, unexpired rates match. Check destination spelling, currency, weight and transit limit.</td></tr><?php endif ?></tbody></table></div><?php endif ?></section>
<div class="columns"><section class="card"><h2><?=$edit?'Edit':'Add'?> a rate</h2><?php startform('rate'); ?><div class="form-grid"><?php foreach(['courier'=>'Courier','service'=>'Service','destination'=>'Destination','currency'=>'Currency'] as $k=>$label)field($label,$k,$edit[$k]??($k==='currency'?'USD':''),'text',true,'maxlength="100"');field('Minimum kg (exclusive)','min_kg',$edit['min_kg']??0,'number',true,'min="0" step="0.001"');field('Maximum kg (inclusive)','max_kg',$edit['max_kg']??5,'number',true,'min="0.001" step="0.001"');field('Flat slab rate','rate',$edit['rate']??'','number',true,'min="0" step="0.01"');field('Transit days (0 = unknown)','transit_days',$edit['transit_days']??'','number',true,'min="0" max="365"');field('Valid until (optional)','valid_until',$edit['valid_until']??'','date'); ?></div><button>Save rate</button></form><p class="muted">Same courier, service, destination, currency and slab updates its rate. To change a slab, disable the old row and add a new one.</p></section>
<section class="card"><h2>Import courier rates</h2><p>Upload CSV, XLS or XLSX. First sheet, maximum 50,000 data rows. The whole file is checked before saving.</p><a href="samples/shipping-rates.csv" download>Download the import template</a><?php startform('import_rates',[],true); ?><label>Rate file · maximum 5 MB<input name="rates" type="file" accept=".csv,.xls,.xlsx" required></label><button class="secondary">Validate & import</button></form><p class="muted">Required headers: courier, service, destination, currency, min_kg, max_kg, rate, transit_days, valid_until. Use decimal numbers without currency symbols. Dates: YYYY-MM-DD text cells. Matching slabs update; other rates remain. Rates do not convert currencies.</p></section></div>
<section class="card table-wrap"><h2>Rate directory</h2><table><thead><tr><th>Courier / service</th><th>Destination</th><th>Weight (kg)</th><th>Rate</th><th>Days</th><th>Valid until</th><th>Active</th></tr></thead><tbody><?php foreach(rows('SELECT * FROM shipping_rates ORDER BY destination,courier,service,min_kg LIMIT 500') as $r): ?><tr><td><a href="index.php?page=shipping&edit=<?=$r['id']?>"><?=e($r['courier'].' / '.$r['service'])?></a></td><td><?=e($r['destination'])?></td><td>&gt; <?=e($r['min_kg'])?>–<?=e($r['max_kg'])?></td><td><?=e($r['currency'].' '.$r['rate'])?></td><td><?=((int)$r['transit_days']===0?'Unknown':e($r['transit_days']))?></td><td><?=e($r['valid_until']??'No expiry')?></td><td><?php startform('rate_toggle',['id'=>$r['id']]); ?><button class="quiet"><?=$r['active']?'Disable':'Enable'?></button></form></td></tr><?php endforeach ?></tbody></table><p class="muted">Showing up to 500 rates.</p></section>
