CREATE DATABASE IF NOT EXISTS aini_wear CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aini_wear;
CREATE TABLE users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 username VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE customers (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL,
 email VARCHAR(160) NOT NULL DEFAULT '', phone VARCHAR(80) NOT NULL DEFAULT '',
 country VARCHAR(100) NOT NULL DEFAULT '', address TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE orders (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(80) NOT NULL UNIQUE,
 customer_id INT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft',
 order_date DATE NOT NULL, due_date DATE NULL, ship_date DATE NULL,
 priority VARCHAR(20) NOT NULL DEFAULT 'normal', destination VARCHAR(100) NOT NULL DEFAULT '',
 tracking VARCHAR(200) NOT NULL DEFAULT '', details TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (customer_id) REFERENCES customers(id), INDEX(due_date), INDEX(status)
) ENGINE=InnoDB;
CREATE TABLE items (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL,
 name VARCHAR(160) NOT NULL, sku VARCHAR(100) NOT NULL DEFAULT '', quantity INT UNSIGNED NOT NULL,
 fabric VARCHAR(200) NOT NULL DEFAULT '', colors VARCHAR(200) NOT NULL DEFAULT '',
 sizes TEXT NOT NULL, requirements TEXT NOT NULL, due_date DATE NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE images (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id INT UNSIGNED NOT NULL,
 filename VARCHAR(100) NOT NULL, original_name VARCHAR(255) NOT NULL, mime VARCHAR(40) NOT NULL,
 FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE component_types (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE components (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id INT UNSIGNED NOT NULL,
 type_id INT UNSIGNED NOT NULL, name VARCHAR(160) NOT NULL,
 quantity INT UNSIGNED NOT NULL DEFAULT 1, details TEXT NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'pending', supplier VARCHAR(160) NOT NULL DEFAULT '',
 due_date DATE NULL, FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
 FOREIGN KEY(type_id) REFERENCES component_types(id)
) ENGINE=InnoDB;
CREATE TABLE step_templates (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 10, active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;
CREATE TABLE item_steps (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id INT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL, position INT NOT NULL DEFAULT 10,
 status VARCHAR(30) NOT NULL DEFAULT 'pending', assignee VARCHAR(120) NOT NULL DEFAULT '',
 start_date DATE NULL, due_date DATE NULL, notes TEXT NOT NULL, completed_at DATETIME NULL,
 FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
 UNIQUE KEY item_step(item_id,name), INDEX(due_date)
) ENGINE=InnoDB;
CREATE TABLE notes (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id INT UNSIGNED NOT NULL,
 body TEXT NOT NULL, followup_date DATE NULL, done TINYINT(1) NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, INDEX(followup_date)
) ENGINE=InnoDB;
CREATE TABLE shipping_rates (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, courier VARCHAR(100) NOT NULL,
 service VARCHAR(100) NOT NULL, destination VARCHAR(100) NOT NULL, currency CHAR(3) NOT NULL,
 min_kg DECIMAL(10,3) NOT NULL, max_kg DECIMAL(10,3) NOT NULL,
 rate_basis VARCHAR(10) NOT NULL DEFAULT 'flat',
 rate DECIMAL(12,2) NOT NULL, transit_days INT UNSIGNED NOT NULL,
 valid_until DATE NULL, active TINYINT(1) NOT NULL DEFAULT 1,
 UNIQUE KEY rate_key(courier,service,destination,currency,min_kg,max_kg), INDEX(destination)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_files (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id INT UNSIGNED NOT NULL,
 filename VARCHAR(100) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 mime VARCHAR(40) NOT NULL,
 bytes INT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB;
